from apowerb.configs.settings import get_settings
import boto3
from botocore.exceptions import ClientError
from io import BytesIO

settings = get_settings()



def _get_s3_client():
    return boto3.client(
        "s3",
        region_name=settings.s3_region,
        endpoint_url=settings.s3_endpoint,
        aws_access_key_id=settings.s3_access_key,
        aws_secret_access_key=settings.s3_access_key_secret,
)


def upload_file_to_s3(file_path: str, s3_key: str) -> str:
    s3=_get_s3_client()
    s3.upload_file(file_path, settings.s3_bucket_name, s3_key)
    return f"s3://{settings.s3_bucket_name}/{s3_key}"

def list_files_in_s3(prefix: str = ""):
    """Every key under ``prefix`` -- following continuation tokens.

    ``list_objects_v2`` returns at most 1000 keys per call and reports the
    rest through ``NextContinuationToken``. Reading only the first page
    silently truncates: the caller gets a short list with no error, and a
    file that exists is reported missing. The busiest agent prefix on dev
    already holds 311 objects.
    """
    s3 = _get_s3_client()
    keys: list[str] = []
    token = None

    while True:
        kwargs = {"Bucket": settings.s3_bucket_name, "Prefix": prefix}
        if token:
            kwargs["ContinuationToken"] = token
        response = s3.list_objects_v2(**kwargs)
        keys.extend(obj["Key"] for obj in response.get("Contents", []))

        if not response.get("IsTruncated"):
            return keys
        token = response.get("NextContinuationToken")
        if not token:
            return keys

def list_objects_in_s3(prefix: str = "") -> list[dict]:
    """Keys under ``prefix`` with their modification time and size.

    ``list_files_in_s3`` returns names only, which forces a caller that
    needs a date to fetch each object. S3 already hands both back in the
    listing response — the artifact library builds an entire screen from
    this, downloading nothing.
    """
    s3 = _get_s3_client()
    objects: list[dict] = []
    token = None

    while True:
        kwargs = {"Bucket": settings.s3_bucket_name, "Prefix": prefix}
        if token:
            kwargs["ContinuationToken"] = token
        response = s3.list_objects_v2(**kwargs)
        for obj in response.get("Contents", []):
            objects.append({
                "key": obj["Key"],
                "last_modified": obj.get("LastModified"),
                "size": obj.get("Size", 0),
            })

        if not response.get("IsTruncated"):
            return objects
        token = response.get("NextContinuationToken")
        if not token:
            return objects


def file_exists_in_s3(s3_key: str) -> bool:
    """True when the object exists.

    A LIST filtered on the key, not a HEAD. head_object is the cheaper
    call and was tried here, but this deployment's S3 endpoint answers
    **400 Bad Request** to it -- for keys that exist as much as for keys
    that do not -- so every existence check raised instead of returning a
    bool, and reading a legacy file 500ed. Measured against the dev bucket
    on 2026-08-07.

    The membership test is exact: in compares whole keys, so a longer
    name sharing the prefix (report.html.bak) does not answer for
    report.html.
    """
    return s3_key in list_files_in_s3(prefix=s3_key)


#the file is in memory or generated by the agent and we store it to s3
def upload_bytes_to_s3(
    content: bytes,
    s3_key: str,
    content_type: str = "application/octet-stream",
    metadata: dict[str, str] | None = None,
) -> str:
    s3 = _get_s3_client()
    file_obj = BytesIO(content)
    extra_args = {"ContentType": content_type}
    if metadata:
        extra_args["Metadata"] = metadata
    s3.upload_fileobj(
        file_obj,
        settings.s3_bucket_name,
        s3_key,
        ExtraArgs=extra_args,
    )
    return s3_key


def get_object_with_metadata(s3_key: str) -> dict:
    """Fetch an object's body along with its content type, custom metadata
    and last-modified timestamp, in a single request.

    Raises ``botocore.exceptions.ClientError`` when the key does not exist —
    callers decide whether to translate that into "not found" or propagate.
    """
    s3 = _get_s3_client()
    response = s3.get_object(Bucket=settings.s3_bucket_name, Key=s3_key)
    return {
        "body": response["Body"].read(),
        "content_type": response.get("ContentType"),
        "metadata": response.get("Metadata", {}),
        "last_modified": response.get("LastModified"),
    }


def head_object_in_s3(s3_key: str) -> dict | None:
    """Return content type / custom metadata / last-modified for an object
    without downloading its body. Returns None if the object does not exist.
    """
    s3 = _get_s3_client()
    try:
        response = s3.head_object(Bucket=settings.s3_bucket_name, Key=s3_key)
    except ClientError as exc:
        error_code = exc.response.get("Error", {}).get("Code")
        if error_code in ("404", "NoSuchKey", "NotFound"):
            return None
        raise
    return {
        "content_type": response.get("ContentType"),
        "metadata": response.get("Metadata", {}),
        "last_modified": response.get("LastModified"),
    }


def download_file_from_s3(s3_key: str) -> bytes:
    """Download file content from S3 as bytes."""
    return get_object_with_metadata(s3_key)["body"]



# Read file as text
def read_text_file_from_s3(s3_key: str, encoding: str = "utf-8") -> str:
    content = download_file_from_s3(s3_key)
    return content.decode(encoding)


# Delete file
def delete_file_from_s3(s3_key: str) -> bool:
    s3 = _get_s3_client()

    s3.delete_object(
        Bucket=settings.s3_bucket_name,
        Key=s3_key,
    )

    return True


